[package]
name = "tetris-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.13"
miniquad = "*"

[profile.dev.package."*"]
opt-level = 3